volumes:
  postgres_data: {}

services:
  fast_api:
    build:
      context: .
      dockerfile: ./compose/fast_api/Dockerfile
    image: crehana_fast_api
    container_name: crehana_fast_api
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: /start.sh

  postgres:
    image: postgres:15-alpine
    container_name: crehana_postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
